### ISSUE TITLE
[BUG] Version 1.1.0 does not work with TYPO3. 6.1

### ISSUE THREAD

**Issue by ste101** [FluidTYPO3/uncache#5]
Im getting this error with 6.1.7. 
#1231259656: The cache configuration for cache "fluid_template" was not an array as expected. (More information)

InvalidArgumentException thrown in file
/var/www/clients/client1/web10/web/typo3_src-6.1.7/typo3/sysext/core/Classes/Cache/CacheManager.php in line 88.

**Comment by NamelessCoder** [comment]
6.1 long since died - uncache will be deprecated soon, suggest switching to the ApplicationContext support in TYPO3 6.2 and above!
