### ISSUE TITLE
Fatal Error in Install Tool if EXT:uncache active

### ISSUE THREAD

**Issue by webian** [FluidTYPO3/uncache#9]
Hi @NamelessCoder !
When EXT:uncache is active the 'Database analyzer' of Install Tool throws this error:
```
Detected Fatal Error
Call to a member function getBackend() on a non-object in /var/www/dummy.com/htdocs/typo3_src/typo3/sysext/core/Classes/Cache/Cache.php on line 95
```

In my workflow I use this tool pretty often while developing and I wonder if is easy to fix this without the need to disable/enable EXT:uncache.

Thanks anyway!

**Comment by xf-** [comment]
Discontinued in favor of development context of TYPO3 core.
